
#Server
server:
  port: 8080
  servlet:
    context-path: /ms-orders/v1

# Database
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ms_orders}
    username: ${SPRING_DATASOURCE_USERNAME:developer}
    password: ${SPRING_DATASOURCE_PASSWORD:developer}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus