
#Server
server:
  port: 8080

# Database
spring:
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_MS_ORDERS_DATABASE:ms_orders}
      port: ${SPRING_DATA_MS_ORDERS_PORT:27017}
      host: ${SPRING_DATA_MS_ORDERS_HOST:mongodb}

kafka:
  clientId: ms-order
  groupId: ms-order
  topicPattern: .*
  bootstrapServers: kafka:9092
