version: '3'
services:
  mysql:
     networks:
       - ms-network
     image: mysql:5.7
     container_name: mysql
     ports: 
       - "3306:3306"    
     environment:
       MYSQL_ROOT_PASSWORD: manager
       MYSQL_DATABASE: api_products
       MYSQL_USER: developer
       MYSQL_PASSWORD: developer

  zookeeper:
     container_name: zookeeper
     networks:
       - ms-network
     image: confluentinc/cp-zookeeper:latest
     environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
     ports:
       - "2181:2181"
  kafka:
     container_name: kafka
     networks:
       - ms-network
     image: confluentinc/cp-kafka:latest
     depends_on:
       - zookeeper
     environment:
       KAFKA_BROKER_ID: 1
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKA_ADVERTISED_HOST_NAME: kafka
     ports:
       - "9092:9092"

  mongodb:
     image: mongo
     networks:
       - ms-network
     ports:
       - "27017:27017"
     container_name: mongodb

  postgresql:
    container_name: postgres
    image: postgres:9.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_customers
    ports:
      - "5432:5432"
    networks:
      - ms-network
    restart: unless-stopped

  api-products:
     networks:
       - ms-network
     image: api-products
     container_name: api-products
     ports:
       - "8081:8081"
       - "8001:8001"
     environment:
       SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/api_products"
       SPRING_DATASOURCE_USERNAME: developer
       SPRING_DATASOURCE_PASSWORD: developer
       JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -XX:+UseParallelGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001 -Xmx128m"
     depends_on:
       - mysql

  ms-orders:
     networks:
       - ms-network
     image: ms-orders
     container_name: ms-orders
     ports:
       - "8080:8080"
       - "8000:8000"
     environment:
       SPRING_DATA_MONGODB_MS_ORDERS_DATABASE: ms_orders
       SPRING_DATA_MS_ORDERS_HOST: mongodb
       SPRING_DATA_MS_ORDERS_PORT: 27017 
       JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -XX:+UseParallelGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Xmx128m"
     depends_on:
       - mongodb

  api-customers:
     networks:
       - ms-network
     image: api-customers
     container_name: api-customers
     ports:
       - "8082:8082"
       - "8002:8002"
     environment:
       SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/api_customers"
       SPRING_DATASOURCE_USERNAME: admin
       SPRING_DATASOURCE_PASSWORD: admin
       JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -XX:+UseParallelGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8002 -Xmx128m"
     depends_on:
       - postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "administrator@sys.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - postgresql
    networks:
      - ms-network
networks: 
    ms-network:
        driver: bridge
