server:
  port: 8081
  .servlet:
    context-path: /api-products/v1

# Database
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/api_products}
    username: ${SPRING_DATASOURCE_USERNAME:developer}
    password: ${SPRING_DATASOURCE_PASSWORD:developer}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
