scrape_configs:
  - job_name: 'ms-orders'
    metrics_path: '/ms-orders/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ms-orders:8080']

  - job_name: 'api-payments'
    metrics_path: '/api-payments/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-payments:8082']

